/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import auxiliares.administradorWeb;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class loginAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form loginAdministrador
     */
    public loginAdministrador() {
        initComponents();
        fondoAdministrador();
        fondoAdministrador2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contra = new javax.swing.JLabel();
        admin1 = new javax.swing.JLabel();
        textAdmin = new javax.swing.JTextField();
        contraAdmin = new javax.swing.JPasswordField();
        logear = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        tituloLogin = new javax.swing.JLabel();
        fondoAdmin = new javax.swing.JLabel();
        fAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contra.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        contra.setForeground(new java.awt.Color(255, 255, 255));
        contra.setText("Contraseña");

        admin1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        admin1.setForeground(new java.awt.Color(255, 255, 255));
        admin1.setText("Administrador");

        textAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAdminActionPerformed(evt);
            }
        });

        logear.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        logear.setText("Ingresar");
        logear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logearActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        salir.setText("Cancelar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        tituloLogin.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        tituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        tituloLogin.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(tituloLogin))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contraAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(fondoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(logear)
                .addGap(53, 53, 53)
                .addComponent(salir))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tituloLogin)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(textAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(contraAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fondoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logear)
                    .addComponent(salir)))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        administradorWeb emple=new administradorWeb();
    private void logearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logearActionPerformed
        String usuario=textAdmin.getText().trim();
        String password=contraAdmin.getText().trim();
        emple.leerDatos();
        if(usuario.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "ALGUN CAMPO ESTA VACIO");       
        }
        else{
            if(usuario.equals(emple.getUsuario()) && password.equals(emple.getContraseña())){
                JOptionPane.showMessageDialog(this, "BIENVENIDO");
                menuProducto menu = new menuProducto();
                menu.setVisible(true);
                menu.setLocationRelativeTo(null);
                loginAdministrador.this.setVisible(false);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTO");
            }
        }
    }//GEN-LAST:event_logearActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        loginAdministrador.this.setVisible(false);
        principal p=new principal();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
    }//GEN-LAST:event_salirActionPerformed

    private void textAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAdminActionPerformed
    
    private void fondoAdministrador(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoAdmin.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoAdmin.getWidth(),fondoAdmin.getHeight(),Image.SCALE_DEFAULT));
        fondoAdmin.setIcon(icono);
    }   
    private void fondoAdministrador2(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoAdministrador.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fAdmin.getWidth(),fAdmin.getHeight(),Image.SCALE_DEFAULT));
        fAdmin.setIcon(icono);
    }        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin1;
    private javax.swing.JLabel contra;
    private javax.swing.JPasswordField contraAdmin;
    private javax.swing.JLabel fAdmin;
    private javax.swing.JLabel fondoAdmin;
    private javax.swing.JButton logear;
    private javax.swing.JButton salir;
    private javax.swing.JTextField textAdmin;
    private javax.swing.JLabel tituloLogin;
    // End of variables declaration//GEN-END:variables
}
