/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import auxiliares.*;
import clases.*;
import estructuras.*;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CARLOS
 */
public class menuProducto extends javax.swing.JFrame {

    /**
     * Creates new form menuProducto
     */
    public menuProducto() {
        initComponents();
        fondoProducto();
        fondoProducto2();
        fondoProducto3();
        fondoCliente();
        fondoCliente2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        clientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tituloProducto = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        talla = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        deporte = new javax.swing.JLabel();
        listTallas = new javax.swing.JComboBox<>();
        textDescrip = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        textStock = new javax.swing.JTextField();
        comboDeport = new javax.swing.JComboBox<>();
        fotoProd = new javax.swing.JLabel();
        fotoProducto = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        precioCompra = new javax.swing.JLabel();
        textCompra = new javax.swing.JTextField();
        fondoProd = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonProducto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        fondoMostrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        botonCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        fclienteRegistrado = new javax.swing.JLabel();
        clientes2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonCli = new javax.swing.JButton();
        fondoCliente = new javax.swing.JLabel();
        alertas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaAlerta = new javax.swing.JTable();
        botonAlertas = new javax.swing.JButton();
        alertaFondo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField28 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jTextField24 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jTextField25 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jTextField23 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTextField18 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jTextField22 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jTextField21 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(null);

        tituloProducto.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        tituloProducto.setForeground(new java.awt.Color(255, 255, 255));
        tituloProducto.setText("Ropa Deportiva");
        jPanel1.add(tituloProducto);
        tituloProducto.setBounds(133, 30, 126, 26);

        descripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        descripcion.setForeground(new java.awt.Color(255, 255, 255));
        descripcion.setText("Descripción : ");
        jPanel1.add(descripcion);
        descripcion.setBounds(39, 93, 156, 26);

        precio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(255, 255, 255));
        precio.setText("Precio de venta :  ");
        jPanel1.add(precio);
        precio.setBounds(39, 164, 156, 26);

        talla.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        talla.setForeground(new java.awt.Color(255, 255, 255));
        talla.setText("Talla : ");
        jPanel1.add(talla);
        talla.setBounds(39, 296, 156, 27);

        stock.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setText("Stock :");
        jPanel1.add(stock);
        stock.setBounds(39, 367, 58, 26);

        deporte.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        deporte.setForeground(new java.awt.Color(255, 255, 255));
        deporte.setText("Deporte : ");
        jPanel1.add(deporte);
        deporte.setBounds(39, 435, 84, 26);

        listTallas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        listTallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        jPanel1.add(listTallas);
        listTallas.setBounds(279, 295, 60, 27);
        jPanel1.add(textDescrip);
        textDescrip.setBounds(278, 96, 179, 26);
        jPanel1.add(textPrecio);
        textPrecio.setBounds(278, 167, 179, 26);

        textStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStockActionPerformed(evt);
            }
        });
        jPanel1.add(textStock);
        textStock.setBounds(279, 370, 179, 26);

        comboDeport.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        comboDeport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fútbol", "basketball", "voleyball", " " }));
        jPanel1.add(comboDeport);
        comboDeport.setBounds(278, 434, 100, 27);

        fotoProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(fotoProd);
        fotoProd.setBounds(527, 93, 190, 196);

        fotoProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        fotoProducto.setText("Cargar Foto");
        fotoProducto.setFocusable(false);
        fotoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(fotoProducto);
        fotoProducto.setBounds(568, 316, 109, 29);

        registrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        registrar.setText("Registrar");
        registrar.setFocusable(false);
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel1.add(registrar);
        registrar.setBounds(495, 452, 95, 29);

        limpiar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.setFocusable(false);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar);
        limpiar.setBounds(638, 452, 98, 29);

        salir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.setFocusable(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir);
        salir.setBounds(565, 510, 98, 29);

        precioCompra.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        precioCompra.setForeground(new java.awt.Color(255, 255, 255));
        precioCompra.setText("Precio de compra : ");
        jPanel1.add(precioCompra);
        precioCompra.setBounds(39, 235, 156, 28);
        jPanel1.add(textCompra);
        textCompra.setBounds(279, 238, 178, 28);
        jPanel1.add(fondoProd);
        fondoProd.setBounds(0, 0, 750, 560);

        clientes.addTab("Registro de Productos", jPanel1);

        jPanel2.setLayout(null);

        botonProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonProducto.setText("Mostrar");
        botonProducto.setFocusable(false);
        botonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductoActionPerformed(evt);
            }
        });
        jPanel2.add(botonProducto);
        botonProducto.setBounds(342, 454, 87, 29);

        tablaProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaProducto);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(63, 54, 640, 351);
        jPanel2.add(fondoMostrar);
        fondoMostrar.setBounds(0, 0, 750, 560);

        clientes.addTab("Mostrar Productos", jPanel2);

        jPanel3.setLayout(null);

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCliente);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(70, 80, 620, 330);

        botonCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonCliente.setText("Mostrar");
        botonCliente.setFocusable(false);
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });
        jPanel3.add(botonCliente);
        botonCliente.setBounds(310, 440, 87, 29);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Cliente:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(70, 30, 123, 26);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Buscar y Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(400, 30, 150, 30);
        jPanel3.add(buscar);
        buscar.setBounds(220, 29, 140, 30);
        jPanel3.add(fclienteRegistrado);
        fclienteRegistrado.setBounds(0, 0, 750, 560);

        clientes.addTab("Clientes Registrados", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        botonCli.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonCli.setText("Mostrar");

        javax.swing.GroupLayout clientes2Layout = new javax.swing.GroupLayout(clientes2);
        clientes2.setLayout(clientes2Layout);
        clientes2Layout.setHorizontalGroup(
            clientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientes2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(clientes2Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(botonCli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fondoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        clientes2Layout.setVerticalGroup(
            clientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientes2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(botonCli))
            .addComponent(fondoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        clientes.addTab("Clientes", clientes2);

        alertas.setLayout(null);

        tablaAlerta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlertaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaAlerta);

        alertas.add(jScrollPane4);
        jScrollPane4.setBounds(70, 60, 616, 386);

        botonAlertas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonAlertas.setText("Mostrar");
        botonAlertas.setFocusable(false);
        botonAlertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlertasActionPerformed(evt);
            }
        });
        alertas.add(botonAlertas);
        botonAlertas.setBounds(318, 485, 87, 29);
        alertas.add(alertaFondo);
        alertaFondo.setBounds(0, 0, 750, 560);

        clientes.addTab("Alertas", alertas);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MapaLima.PNG"))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("         RIMAC");

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField30)
                    .addComponent(jTextField29)
                    .addComponent(jTextField28)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField30)
                .addContainerGap())
        );

        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("        CALLAO");

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField19)
                    .addComponent(jTextField17)
                    .addComponent(jTextField24)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField19)
                .addContainerGap())
        );

        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("      SAN MIGUEL");

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField27)
                    .addComponent(jTextField26)
                    .addComponent(jTextField25)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField27)
                .addContainerGap())
        );

        jTextField23.setText(" MercadLib S.A.C");
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("    JESUS MARIA");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField16)
                    .addComponent(jTextField15)
                    .addComponent(jTextField23, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField16)
                .addContainerGap())
        );

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("    EL AGUSTINO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField5)
                    .addComponent(jTextField3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("    SANTA ANITA");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField13)
                    .addComponent(jTextField11)
                    .addComponent(jTextField22)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField13)
                .addContainerGap())
        );

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("    MIRAFLORES");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jTextField20)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addContainerGap())
        );

        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("      SAN BORJA");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField9)
                    .addComponent(jTextField7)
                    .addComponent(jTextField21)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9)
                .addContainerGap())
        );

        jButton2.setText("Mostrar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        clientes.addTab("Ruta de Entregas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fondoProducto(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoProducto2.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoProd.getWidth(),fondoProd.getHeight(),Image.SCALE_DEFAULT));
        fondoProd.setIcon(icono);
    }
    private void fondoProducto2(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoProducto.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoMostrar.getWidth(),fondoMostrar.getHeight(),Image.SCALE_DEFAULT));
        fondoMostrar.setIcon(icono);
    }
    private void fondoProducto3(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoAlerta.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(alertaFondo.getWidth(),alertaFondo.getHeight(),Image.SCALE_DEFAULT));
        alertaFondo.setIcon(icono);
    }
    private void fondoCliente(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fonCliente.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fclienteRegistrado.getWidth(),fclienteRegistrado.getHeight(),Image.SCALE_DEFAULT));
        fclienteRegistrado.setIcon(icono);
    }
    private void fondoCliente2(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fonCliente2.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoCliente.getWidth(),fondoCliente.getHeight(),Image.SCALE_DEFAULT));
        fondoCliente.setIcon(icono);
    }
    private void botonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductoActionPerformed
        try {
            archivos ar=new archivos();
            listaSimple<Producto>lista=ar.cargarProducto();
            int i=0;
            int suma=0;
            for (Nodo<Producto>au = lista.getCab();au!=null;au=au.getSiguiente()) {
                suma=suma+au.getDato().contarTallas();
            }
            String Matriz[][]=new String[suma][6];
            for (Nodo<Producto>au = lista.getCab();au!=null;au=au.getSiguiente()) {                
                for (int j = 0; j < au.getDato().tallas(); j++) {
                    if(au.getDato().getTalla(j)!=null && String.valueOf(au.getDato().getStock(j))!=null){
                        Matriz[i][0]=au.getDato().getDescrip();
                        Matriz[i][1]=au.getDato().getTalla(j);
                        Matriz[i][2]=String.valueOf(au.getDato().getPrecio(j));
                        Matriz[i][3]=String.valueOf(au.getDato().getPrecioCompra(j));
                        Matriz[i][4]=String.valueOf(au.getDato().getStock(j));
                        Matriz[i][5]=au.getDato().getDeport();
                        i++;
                    }
                }
                
            }
            tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
                Matriz,
                new String [] {
                    "DESCRIPCION", "TALLA", "PRECIO VENTA","PRECIO COMPRA", "STOCK", "DEPORTE"
                }
            ));
        } catch (IOException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonProductoActionPerformed
    File archivo;
    private void fotoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoProductoActionPerformed
        int resultado;
        cargaFotos ventana=new cargaFotos();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("JPG y PNG","jpg","png");
        ventana.jFileChooser1.setFileFilter(filtro);
        resultado=ventana.jFileChooser1.showOpenDialog(null);
        if(JFileChooser.APPROVE_OPTION==resultado){
            archivo=ventana.jFileChooser1.getSelectedFile();
            try{
                ImageIcon icon=new ImageIcon(archivo.toString());
                Icon icono=new ImageIcon(icon.getImage().getScaledInstance(fotoProd.getWidth(),fotoProd.getHeight() , Image.SCALE_DEFAULT));
                fotoProd.setText(null);
                fotoProd.setIcon(icono);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error abriendo la imagen"+ex);
            }
        }
    }//GEN-LAST:event_fotoProductoActionPerformed
    listaSimple<Producto> list=new listaSimple();
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        if(textDescrip.getText().isEmpty() || textPrecio.getText().isEmpty() || textStock.getText().isEmpty() || textCompra.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ALGUN CAMPO ESTA VACIO");
        }
        else{
            try{     
            FileReader nb = new FileReader("bandera1.txt");
            BufferedReader a = new BufferedReader(nb); 
            String lec=a.readLine();
            a.close();
            if(lec.equals("Si")&&Integer.parseInt(textStock.getText())>=10 && Double.parseDouble(textPrecio.getText())>=0
               && Double.parseDouble(textCompra.getText())>=0){
                Producto pro=new Producto();
                pro.setDescrip(textDescrip.getText());
                pro.setStock(Integer.parseInt(textStock.getText()),listTallas.getSelectedIndex());
                pro.setPrecio(Double.parseDouble(textPrecio.getText()),listTallas.getSelectedIndex());
                pro.setDeport(comboDeport.getSelectedItem().toString());
                pro.setTalla(listTallas.getSelectedItem().toString(),listTallas.getSelectedIndex());
                pro.setPrecioCompra(Double.parseDouble(textCompra.getText()),listTallas.getSelectedIndex());
                pro.setFoto(archivo.toString());
                list.insertarFinal(pro);
                archivos archi=new archivos();
                archi.guardarProducto(list);
                FileWriter sc = new FileWriter("bandera1.txt");
                BufferedWriter c = new BufferedWriter(sc);
                c.write("No");
                c.close();
                JOptionPane.showMessageDialog(this, "Registro Correcto");
            }
            
            else{
                if(lec.equals("No")&&Integer.parseInt(textStock.getText())>=10 && Double.parseDouble(textPrecio.getText())>=0
               && Double.parseDouble(textCompra.getText())>=0){
                    archivos ar=new archivos();
                list=ar.cargarProducto();
                boolean to=true;
                for(Nodo<Producto> sparda=list.getCab();sparda!=null;sparda=sparda.getSiguiente()){
                    if(textDescrip.getText().equals(sparda.getDato().getDescrip())&&
                       Double.parseDouble(textPrecio.getText())==sparda.getDato().getPrecio(listTallas.getSelectedIndex())&&
                       Double.parseDouble(textCompra.getText())==sparda.getDato().getPrecioCompra(listTallas.getSelectedIndex())&&
                       listTallas.getSelectedItem().toString().equals(sparda.getDato().getTalla(listTallas.getSelectedIndex()))&&
                       fotoProd.getIcon()!=null && comboDeport.getSelectedItem().toString().equals(sparda.getDato().getDeport())){
                       sparda.getDato().setStock(sparda.getDato().getStock(listTallas.getSelectedIndex())+Integer.parseInt(textStock.getText()),listTallas.getSelectedIndex());
                       to=false;
                       JOptionPane.showMessageDialog(this, "Se ha aumentado el stock.");
                    }
                    else{
                        if(textDescrip.getText().equals(sparda.getDato().getDescrip())&&
                       archivo.toString().equals(sparda.getDato().getFoto())&& comboDeport.getSelectedItem().toString().equals(sparda.getDato().getDeport())){
                        sparda.getDato().setPrecio(Double.parseDouble(textPrecio.getText()),listTallas.getSelectedIndex());
                        sparda.getDato().setDeport(comboDeport.getSelectedItem().toString());
                        sparda.getDato().setTalla(listTallas.getSelectedItem().toString(),listTallas.getSelectedIndex());
                        sparda.getDato().setPrecioCompra(Double.parseDouble(textCompra.getText()),listTallas.getSelectedIndex());
                        sparda.getDato().setStock(Integer.parseInt(textStock.getText()),listTallas.getSelectedIndex());
                       to=false;
                       JOptionPane.showMessageDialog(this, "Se ha registrado talla nueva.");
                    }
                    }
                }
                if(to==true){
                    Producto pro=new Producto();
                    pro.setDescrip(textDescrip.getText());
                    pro.setStock(Integer.parseInt(textStock.getText()),listTallas.getSelectedIndex());
                    pro.setPrecio(Double.parseDouble(textPrecio.getText()),listTallas.getSelectedIndex());
                    pro.setDeport(comboDeport.getSelectedItem().toString());
                    pro.setTalla(listTallas.getSelectedItem().toString(),listTallas.getSelectedIndex());
                    pro.setPrecioCompra(Double.parseDouble(textCompra.getText()),listTallas.getSelectedIndex());
                    pro.setFoto(archivo.toString());
                    list.insertarFinal(pro);
                    JOptionPane.showMessageDialog(this, "Registro Correcto");
                }
                archivos archi=new archivos();
                archi.guardarProducto(list);
                }
                if(Double.parseDouble(textPrecio.getText())<0 || Double.parseDouble(textCompra.getText())<0){
                    JOptionPane.showMessageDialog(this, "No esta permitido ingresar numeros negativos.");
                }
                if(Integer.parseInt(textStock.getText())<10){
                    JOptionPane.showMessageDialog(this, "El valor minimo del stock es de 10.");
                }
            }
           } catch (FileNotFoundException ex) {    
                Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(NumberFormatException a){
               JOptionPane.showMessageDialog(this, "Ingrese datos numéricos donde corresponda");
           }     
            
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        textDescrip.setText("");
        textStock.setText("");
        textPrecio.setText("");
        fotoProd.setIcon(null);
        textCompra.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        principal pri=new principal();
        pri.setVisible(true);
        pri.setLocationRelativeTo(null);
        menuProducto.this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        try {
            archivos ar=new archivos();
            ListaDoble<clienteRegistrado> cli2=ar.cargarCliente();
            String Matriz[][]=new String[cli2.Contar()][3];
            NodoDoble<clienteRegistrado> a=cli2.getInicio();
            for(int i=0;i<cli2.Contar() && a!=null;i++){  
                Matriz[i][0]=a.getDato().getNombre();
                Matriz[i][1]=String.valueOf(a.getDato().getDni());
                Matriz[i][2]=a.getDato().getCorreo();
                a=a.getSiguiente();
            }   
            tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
                Matriz,
                new String [] {
                    "NOMBRE", "DNI", "CORREO"
                }
            ));
        } catch (IOException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonClienteActionPerformed

    private void textStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//         String nombre = buscar.getText();
//         Cliente cliente;
//         Vector m = new Vector();
//         cliente=m.buscar(nombre);
//         if( !m.estavacio())
//         {
//             if( cliente != null)
//             JOptionPane.showMessageDialog(null, "Cliente Encontrado", "Atencion", JOptionPane.INFORMATION_MESSAGE);
//             else
//             JOptionPane.showMessageDialog(null, "Cliente no encontrado", "Atencion", JOptionPane.INFORMATION_MESSAGE);
//         
//         try {
//            archivos ar=new archivos();
//            listaSimple<Producto> lista=ar.cargarProducto();
//            String Matriz[][]=new String[lista.Contar()][6];
//            Nodo<Producto> a=cliente.getCarrito().getFrente();
//            
//            for (int i = 0; i < cliente.getCarrito().Contar() && a!=null; i++) {
//                String tallas=new String();
//                Matriz[i][0]=a.getDato().getDescrip();
//                for (int j = 0; j < 6; j++) {
//                    if(a.getDato().getTalla(j)!=null){
//                        tallas=tallas+a.getDato().getTalla(j)+", ";
//                    }else{
//                        if(a.getDato().getTalla(j)!=null && j==5){
//                            tallas=tallas+a.getDato().getTalla(j);
//                        }
//                    }
//                }
//                Matriz[i][1]=tallas;
//                Matriz[i][2]=String.valueOf(a.getDato().getPrecio());
//                Matriz[i][3]=String.valueOf(a.getDato().getPrecioCompra());
//                Matriz[i][4]=String.valueOf(a.getDato().getStock());
//                Matriz[i][5]=a.getDato().getDeport();
//                a=a.getSiguiente();
//            }
//            tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
//                Matriz,
//                new String [] {
//                    "DESCRIPCION", "TALLA", "PRECIO VENTA","PRECIO COMPRA", "STOCK", "DEPORTE"
//                }
//            ));
//        } catch (IOException ex) {
////            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
////            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
//        }
//         }
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        fact io=new fact();
        io.setVisible(true);
        io.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_tablaClienteMouseClicked
    boolean t=true;
    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        try {
            archivos ar=new archivos();
            listaSimple<Producto> lista=ar.cargarProducto();           
            for (Nodo<Producto> a=lista.getCab();a!=null && t==true;a=a.getSiguiente()) {
                for (int i = 0; i < a.getDato().tallas(); i++) {
                    if(a.getDato().getStock(i)==10){
                        JOptionPane.showMessageDialog(null,"Pedir más productos al proveedor");
                        t=false;
                    }
                }
            }
        } catch (IOException | ClassNotFoundException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        
    }//GEN-LAST:event_jPanel1MouseExited
//    private int contarAlerta() throws IOException, FileNotFoundException, ClassNotFoundException{
//        archivos ar=new archivos();
//        listaSimple<Producto> lista=ar.cargarProducto();
//        String Matriz[][]=new String[lista.Contar()][6];
//        int i=0;
//        for (Nodo<Producto> a=lista.getCab(); a!=null; a=a.getSiguiente()) {
//                if(a.getDato().getStock()==10){
//                    String tallas=new String();
//                    Matriz[i][0]=a.getDato().getDescrip();
//                    for (int j = 0; j < 6; j++) {
//                        if(a.getDato().getTalla(j)!=null){
//                            tallas=tallas+a.getDato().getTalla(j)+", ";
//                        }else{
//                            if(a.getDato().getTalla(j)!=null && j==5){
//                                tallas=tallas+a.getDato().getTalla(j);
//                            }
//                        }
//                    }
//                    Matriz[i][1]=tallas;
//                    Matriz[i][2]=String.valueOf(a.getDato().getPrecio());
//                    Matriz[i][3]=String.valueOf(a.getDato().getPrecioCompra());
//                    Matriz[i][4]=String.valueOf(a.getDato().getStock());
//                    Matriz[i][5]=a.getDato().getDeport();
//                    ap.insertarFinal(a.getDato());
//                    i++;
//                }                
//        }
//        return i;
//    }
    private void botonAlertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlertasActionPerformed
        try {
            archivos ar=new archivos();
            listaSimple<Producto> lista=ar.cargarProducto();
            int i=0;
            int suma=0;
            for (Nodo<Producto>au = lista.getCab();au!=null;au=au.getSiguiente()) {
                for (int j = 0; j < au.getDato().tallas(); j++) {
                    if(au.getDato().getStock(j)==10){
                        suma=suma+1;
                    }
                }
            }
            String Matriz[][]=new String[suma][6];
            for (Nodo<Producto>au = lista.getCab();au!=null;au=au.getSiguiente()) {                
                for (int j = 0; j < au.getDato().tallas(); j++) {
                    if(au.getDato().getTalla(j)!=null && au.getDato().getStock(j)==10){
                        Matriz[i][0]=au.getDato().getDescrip();
                        Matriz[i][1]=au.getDato().getTalla(j);
                        Matriz[i][2]=String.valueOf(au.getDato().getPrecio(j));
                        Matriz[i][3]=String.valueOf(au.getDato().getPrecioCompra(j));
                        Matriz[i][4]=String.valueOf(au.getDato().getStock(j));
                        Matriz[i][5]=au.getDato().getDeport();
                        i++;
                    }
                }
                
            }
            tablaAlerta.setModel(new javax.swing.table.DefaultTableModel(
                Matriz,
                new String [] {
                    "DESCRIPCION", "TALLA", "PRECIO VENTA","PRECIO COMPRA", "STOCK", "DEPORTE"
                }
            ));
        } catch (IOException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAlertasActionPerformed
    private void tablaAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlertaMouseClicked
        listaSimple<Producto>auxiliar=new listaSimple();
        archivos j=new archivos();
        try {
            auxiliar=j.cargarProducto();
            int y=0;
        int x=0;
        textDescrip.setText(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),0)));
        textPrecio.setText(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),2)));
        textCompra.setText(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),3)));
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),1)).equals("XS")){
            y=0;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),1)).equals("S")){
            y=1;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),1)).equals("M")){
            y=2;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),1)).equals("L")){
            y=3;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),1)).equals("XL")){
            y=4;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),1)).equals("XXL")){
            y=5;
        }
        listTallas.setSelectedIndex(y);
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),5)).equals("fútbol")){
           x=0;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),5)).equals("basketball")){
            x=1;
        }
        if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),5)).equals("voleyball")){
            x=2;
        }
        comboDeport.setSelectedIndex(x);
        String ima="";
        for (Nodo<Producto>au = auxiliar.getCab();au!=null;au=au.getSiguiente()) {
            if(String.valueOf(tablaAlerta.getValueAt(tablaAlerta.getSelectedRow(),0)).equals(au.getDato().getDescrip())){
                ima=au.getDato().getFoto();
            }
        }
        ImageIcon icon=new ImageIcon(ima);
        Icon icono=new ImageIcon(icon.getImage().getScaledInstance(fotoProd.getWidth(), fotoProd.getHeight(),Image.SCALE_DEFAULT));
        fotoProd.setText("");
        fotoProd.setIcon(icono);
        JOptionPane.showMessageDialog(null,"Hacer pedido al proveedor");
        } catch (IOException ex) {
            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_tablaAlertaMouseClicked

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        archivos tesh = new archivos();
        try {
            Grafo nuevo = tesh.cargarEntregas();
            for (int i = 0; i < nuevo.numVertices; i++) {
                String temp;
                int indInicio;
                int indFin;
                temp = nuevo.vertices[i].getNombre();
                if(i==0){
                    indInicio = 5;
                    indFin = 5;
                }else{
                    indInicio = nuevo.vertices[i-1].getIndice();
                    indFin =nuevo.vertices[i].getIndice();
                }
                switch (temp){
                    case "CALLAO":
                        jTextField24.setText("Ent. Nro: "+(i+1));
                        jTextField17.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                        break;
                    case "RIMAC":
                        jTextField28.setText("Ent. Nro: "+(i+1));
                        jTextField29.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                        break;
                    case "SAN MIGUEL":
                        jTextField25.setText("Ent. Nro: "+(i+1));
                        jTextField26.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                        break;
                    case "JESUS MARIA":
                        jTextField15.setText("Ent. Nro: "+(i+1));
                        jTextField16.setText("Recorrido: "+0);
                        break;
                    case "EL AGUSTINO":
                        jTextField18.setText("Ent. Nro: "+(i+1));
                        jTextField3.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                        break;
                    case "SANTA ANITA":
                        jTextField22.setText("Ent. Nro: "+(i+1));
                        jTextField11.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                        break;
                    case "SAN BORJA":
                        jTextField21.setText("Ent. Nro: "+(i+1));
                        jTextField7.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                        break;
                    case "MIRAFLORES":
                        jTextField20.setText("Ent. Nro: "+(i+1));
                        jTextField1.setText("Recorrido: "+String.valueOf(nuevo.aristas[indInicio][indFin].getPeso()));
                }
            }
        } catch (IOException ex) {
  //          Logger.getLogger(RutaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
  //          Logger.getLogger(RutaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaFondo;
    private javax.swing.JPanel alertas;
    private javax.swing.JButton botonAlertas;
    private javax.swing.JButton botonCli;
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonProducto;
    private javax.swing.JTextField buscar;
    private javax.swing.JTabbedPane clientes;
    private javax.swing.JPanel clientes2;
    private javax.swing.JComboBox<String> comboDeport;
    private javax.swing.JLabel deporte;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel fclienteRegistrado;
    private javax.swing.JLabel fondoCliente;
    private javax.swing.JLabel fondoMostrar;
    private javax.swing.JLabel fondoProd;
    private javax.swing.JLabel fotoProd;
    private javax.swing.JButton fotoProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton limpiar;
    private javax.swing.JComboBox<String> listTallas;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precioCompra;
    private javax.swing.JButton registrar;
    private javax.swing.JButton salir;
    private javax.swing.JLabel stock;
    private javax.swing.JTable tablaAlerta;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JLabel talla;
    private javax.swing.JTextField textCompra;
    private javax.swing.JTextField textDescrip;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textStock;
    private javax.swing.JLabel tituloProducto;
    // End of variables declaration//GEN-END:variables
}
