/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import auxiliares.clienteRegistrado;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author CARLOS
 */
public class menuComprar extends javax.swing.JFrame {

    /**
     * Creates new form menuComprar
     */
    public menuComprar(clienteRegistrado y) {
        initComponents();
        yu=y;
        fondoCredito();
        fondoTransferencia();
        fondoEfectivo();
    }

    public menuComprar() {
        initComponents();
        fondoCredito();
        fondoTransferencia();
        fondoEfectivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPago = new javax.swing.JLabel();
        tarjeta = new javax.swing.JLabel();
        transferencia = new javax.swing.JLabel();
        botonTarjeta = new javax.swing.JButton();
        botonTransferencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonEfectivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloPago.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        tituloPago.setText("Medios de Pago ");

        tarjeta.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tarjeta.setText("Tarjeta");

        transferencia.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        transferencia.setText("Transferencia bancaria ");

        botonTarjeta.setFocusable(false);
        botonTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTarjetaActionPerformed(evt);
            }
        });

        botonTransferencia.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Presencial");

        botonEfectivo.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(tituloPago))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(botonTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(botonEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(tituloPago)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(botonEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fondoCredito(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/credito.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(botonTarjeta.getWidth(),botonTarjeta.getHeight(),Image.SCALE_DEFAULT));
        botonTarjeta.setIcon(icono);
    }
    private void fondoTransferencia(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/transferencia.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(botonTransferencia.getWidth(),botonTransferencia.getHeight(),Image.SCALE_DEFAULT));
        botonTransferencia.setIcon(icono);
    }
    private void fondoEfectivo(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/botonEfectivo.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(botonEfectivo.getWidth(),botonEfectivo.getHeight(),Image.SCALE_DEFAULT));
        botonEfectivo.setIcon(icono);
    }
    clienteRegistrado yu=new clienteRegistrado();
    private void botonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTarjetaActionPerformed
        tarjetaComprar tarj = new tarjetaComprar(yu);
        tarj.setVisible(true);
        tarj.setLocationRelativeTo(null);
        menuComprar.this.setVisible(false);
    }//GEN-LAST:event_botonTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuComprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEfectivo;
    private javax.swing.JButton botonTarjeta;
    private javax.swing.JButton botonTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tarjeta;
    private javax.swing.JLabel tituloPago;
    private javax.swing.JLabel transferencia;
    // End of variables declaration//GEN-END:variables
}
