/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import auxiliares.archivos;
import auxiliares.clienteRegistrado;
import clases.Pedido;
import clases.Producto;
import estructuras.Cola;
import estructuras.Nodo;
import estructuras.listaSimple;
import java.awt.Image;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class sitioWeb2 extends javax.swing.JFrame {

    /**
     * Creates new form sitioWeb2
     */
    public sitioWeb2(clienteRegistrado t) {
        initComponents();
        cliente=t;
        fondoCarrito();
        fondoPWeb2();
    }

    private sitioWeb2() {
        initComponents();
        fondoCarrito();
        fondoPWeb2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logearse = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProducto = new javax.swing.JList<>();
        tituloProducto = new javax.swing.JLabel();
        nombreProd = new javax.swing.JLabel();
        precioProd = new javax.swing.JLabel();
        tallaProd = new javax.swing.JLabel();
        numeroProd = new javax.swing.JLabel();
        deporteProd = new javax.swing.JLabel();
        textPrecio = new javax.swing.JLabel();
        textDeporte = new javax.swing.JLabel();
        botonCarrito = new javax.swing.JButton();
        tituloCarrito = new javax.swing.JLabel();
        mostrarProd = new javax.swing.JLabel();
        mostrarProductos = new javax.swing.JButton();
        textCantidad = new javax.swing.JTextField();
        alerta = new javax.swing.JLabel();
        jButtonRetorno = new javax.swing.JButton();
        textDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTalla = new javax.swing.JList<>();
        fondoWeb2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        botonComprar = new javax.swing.JButton();
        botCarrito = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNroCompras = new javax.swing.JTextField();
        jTextFieldIGV = new javax.swing.JTextField();
        jTextFieldDescuento = new javax.swing.JTextField();
        jTextFieldImporte = new javax.swing.JTextField();
        jTextFieldNeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProductoMouseClicked(evt);
            }
        });
        listaProducto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProductoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaProducto);

        tituloProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tituloProducto.setForeground(new java.awt.Color(255, 255, 255));
        tituloProducto.setText("Lista de Productos");

        nombreProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nombreProd.setForeground(new java.awt.Color(255, 255, 255));
        nombreProd.setText("Descripción : ");

        precioProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        precioProd.setForeground(new java.awt.Color(255, 255, 255));
        precioProd.setText("Precio : ");

        tallaProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tallaProd.setForeground(new java.awt.Color(255, 255, 255));
        tallaProd.setText("Talla : ");

        numeroProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        numeroProd.setForeground(new java.awt.Color(255, 255, 255));
        numeroProd.setText("Cantidad : ");

        deporteProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        deporteProd.setForeground(new java.awt.Color(255, 255, 255));
        deporteProd.setText("Deporte : ");

        textPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        textPrecio.setForeground(new java.awt.Color(255, 255, 255));

        textDeporte.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        botonCarrito.setFocusable(false);
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });

        tituloCarrito.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tituloCarrito.setForeground(new java.awt.Color(255, 255, 255));
        tituloCarrito.setText("Añadir al carrito");

        mostrarProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        mostrarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarProdMouseClicked(evt);
            }
        });

        mostrarProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mostrarProductos.setText("Mostrar");
        mostrarProductos.setFocusable(false);
        mostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProductosActionPerformed(evt);
            }
        });

        textCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCantidadActionPerformed(evt);
            }
        });

        alerta.setForeground(new java.awt.Color(255, 51, 51));

        jButtonRetorno.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jButtonRetorno.setText("Regresar");
        jButtonRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornoActionPerformed(evt);
            }
        });

        textDescripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        textDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        listTalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTallaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listTalla);

        fondoWeb2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(numeroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(mostrarProductos))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(botonCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(precioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(tituloCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(deporteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(662, 662, 662)
                .addComponent(mostrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(tituloProducto))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(jButtonRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(tallaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(textDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fondoWeb2, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numeroProd)
                .addGap(9, 9, 9)
                .addComponent(alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(mostrarProductos))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(botonCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(precioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(tituloCarrito))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(deporteProd))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(mostrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tituloProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jButtonRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(tallaProd))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(textDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fondoWeb2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Logearse.addTab("Productos", jPanel1);

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaCarrito);

        botonComprar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        botonComprar.setText("Comprar");
        botonComprar.setFocusable(false);
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        botCarrito.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        botCarrito.setText("Mostrar Carrito");
        botCarrito.setFocusable(false);
        botCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCarritoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("RESUMEN DE PEDIDO"));

        jLabel1.setText("Nro de Productos:");

        jLabel2.setText("Importe:");

        jLabel3.setText("IGV: ");

        jLabel4.setText("Descuento:");

        jLabel5.setText("Monto Neto:");

        jTextFieldNroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNroComprasActionPerformed(evt);
            }
        });

        jTextFieldDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIGV)
                            .addComponent(jTextFieldDescuento)
                            .addComponent(jTextFieldNeto)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNroCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jTextFieldImporte)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNroCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(botonComprar)
                .addGap(82, 82, 82)
                .addComponent(botCarrito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonComprar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Logearse.addTab("Carrito", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logearse)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logearse)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fondoPWeb2(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoProducto.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoWeb2.getWidth(),fondoWeb2.getHeight(),Image.SCALE_DEFAULT));
        fondoWeb2.setIcon(icono);
    }
    private void fondoCarrito(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/carrito.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(botonCarrito.getWidth(),botonCarrito.getHeight(),Image.SCALE_DEFAULT));
        botonCarrito.setIcon(icono);
    }
    int bandera=-1;
    boolean b=true;
    private void listaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProductoMouseClicked
        if(b==false && bandera!=listaProducto.getSelectedIndex()){
            textPrecio.setText("");
            modelLista2.clear();
            textCantidad.setText("");
        }
        if(evt.getClickCount()==1 && bandera!=listaProducto.getSelectedIndex()){
           int indice=listaProducto.getSelectedIndex();
            lk=pro.buscar(indice);
            textDescripcion.setText(lk.getDato().getDescrip());
            for (int i = 0; i < lk.getDato().tallas(); i++) {
                if(lk.getDato().getTalla(i)!=null){
                    modelLista2.addElement(lk.getDato().getTalla(i));
                }
            }
            listTalla.setModel(modelLista2);
            textDeporte.setText(lk.getDato().getDeport());
            bandera=listaProducto.getSelectedIndex();
            b=false;
            try {
                ImageIcon icon=new ImageIcon(lk.getDato().getFoto());
                Icon icono=new ImageIcon(icon.getImage().getScaledInstance(mostrarProd.getWidth(), mostrarProd.getHeight(),Image.SCALE_DEFAULT));
                mostrarProd.setText(null);
                mostrarProd.setIcon(icono);
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen"+e);
            }
        }
    }//GEN-LAST:event_listaProductoMouseClicked
    DefaultListModel modelLista2= new DefaultListModel();
    Nodo<Producto> lk=new Nodo<Producto>();
    private void listaProductoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProductoValueChanged
        
    }//GEN-LAST:event_listaProductoValueChanged
    clienteRegistrado cliente=new clienteRegistrado();
    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        try{
        int indice=listaProducto.getSelectedIndex();
        Nodo<Producto> lk=pro.buscar(indice);
        Pedido t=new Pedido();
        for (int i = 0; i < lk.getDato().tallas(); i++) {
            if(Integer.valueOf(textCantidad.getText())>lk.getDato().getStock(i) && listTalla.getSelectedValue().equals(lk.getDato().getTalla(i))){
                JOptionPane.showMessageDialog(this, "Lo sentimos, ha sobrepasado nuestro stock");
            }
            else{
                if(listTalla.getSelectedValue().equals(lk.getDato().getTalla(i))){
                    int sum=lk.getDato().getStock(i)-Integer.parseInt(textCantidad.getText());
                if(sum<10){
                    JOptionPane.showMessageDialog(this, "Lo sentimos, pero alcanzo el limite de nuestro stock.");
                }
                else{
                    t.setDescrip(lk.getDato().getDescrip());
                    t.setTalla(listTalla.getSelectedValue());
                    t.setDeport(lk.getDato().getDeport());
                    int y=0;
                    if(listTalla.getSelectedValue()=="XS"){
                        y=0;
                    }
                    if(listTalla.getSelectedValue()=="S"){
                        y=1;
                    }
                    if(listTalla.getSelectedValue()=="L"){
                        y=2;
                    }
                    if(listTalla.getSelectedValue()=="M"){
                        y=3;
                    }
                    if(listTalla.getSelectedValue()=="XL"){
                        y=4;
                    }
                    if(listTalla.getSelectedValue()=="XXL"){
                        y=5;
                    }
                    t.setPrecio(lk.getDato().getPrecio(y));
                    t.setPrecioTot(lk.getDato().getPrecio(y)*(1.0*Integer.parseInt(textCantidad.getText())));
                    t.setCantidad(Integer.parseInt(textCantidad.getText()));
                    colas.encolar(t);
                    archivos hi=new archivos();
                    hi.guardarCompra(colas);
                    JOptionPane.showMessageDialog(this, "Articulo añadida al carrito");
            }
                }            
        }
        }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese datos números donde corresponda.");
        }
    }//GEN-LAST:event_botonCarritoActionPerformed

    private void mostrarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarProdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarProdMouseClicked
    listaSimple<Producto> pro=new listaSimple();
    DefaultListModel modelLista= new DefaultListModel();
    private void mostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProductosActionPerformed
        try {
            archivos po=new archivos();
            pro=po.cargarProducto();
            for(Nodo<Producto> lk=pro.getCab();lk!=null;lk=lk.getSiguiente()){
                modelLista.addElement(lk.getDato().getDescrip());
            }
            listaProducto.setModel(modelLista);
            mostrarProductos.setVisible(false);
        } catch (IOException | ClassNotFoundException ex) {

        }
    }//GEN-LAST:event_mostrarProductosActionPerformed

    private void textCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCantidadActionPerformed

    private void jButtonRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornoActionPerformed
        menuCliente mo= new menuCliente();
        mo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRetornoActionPerformed

    private void listTallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTallaMouseClicked
        if(evt.getClickCount()==1){
            int y=0;
            if(listTalla.getSelectedValue().equals("XS")){
                y=0;
            }
            if(listTalla.getSelectedValue().equals("S")){
                y=1;
            }
            if(listTalla.getSelectedValue().equals("L")){
                y=3;
            }
            if(listTalla.getSelectedValue().equals("M")){
                y=2;
            }
            if(listTalla.getSelectedValue().equals("XL")){
                y=4;
            }
            if(listTalla.getSelectedValue().endsWith("XXL")){
                y=5;
            }
        textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
        }
    }//GEN-LAST:event_listTallaMouseClicked
    
    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        this.dispose();
        menuComprar com=new menuComprar(cliente);
        com.setVisible(true);
        com.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonComprarActionPerformed
    Cola<Pedido> colas=new Cola();
    private void botCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCarritoActionPerformed
        try {
            int nroProductos=0;
            double precioTot=0,IGVGeneral=0,IGV=0;
            archivos ar=new archivos();
            Cola<Pedido> lista=ar.cargarCompra();
            String Matriz[][]=new String[lista.Contar()][6];
            Nodo<Pedido> a=lista.getFrente();
            for (int i = 0; i < lista.Contar() && a!=null; i++) {
                Matriz[i][0]=a.getDato().getDescrip();
                Matriz[i][1]=a.getDato().getTalla();
                Matriz[i][2]=String.valueOf(a.getDato().getPrecio());
                Matriz[i][3]=String.valueOf(a.getDato().getPrecioTot());
                Matriz[i][4]=String.valueOf(a.getDato().getCantidad());
                Matriz[i][5]=a.getDato().getDeport();
                nroProductos=nroProductos+a.getDato().getCantidad();
                precioTot=precioTot+a.getDato().getPrecioTot();
                IGV = calcularIGV(a.getDato());

                IGVGeneral = IGVGeneral+ IGV;
                a=a.getSiguiente();
            }
            tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
                Matriz,
                new String [] {
                    "DESCRIPCION", "TALLA", "PRECIO UNITARIO", "PRECIO TOTAL", "CANTIDAD", "DEPORTE"
                }
            ));
            jTextFieldNroCompras.setText(String.valueOf(nroProductos));
            jTextFieldImporte.setText(String.valueOf(precioTot));
            jTextFieldIGV.setText(String.valueOf(IGVGeneral));
            jTextFieldDescuento.setText("10%");
            jTextFieldNeto.setText(String.valueOf(redondearDecimales((precioTot+IGVGeneral)*0.9,2)));
        } catch (IOException ex) {
            //            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            //            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botCarritoActionPerformed
       
    public  double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
       
    public double calcularIGV(Pedido aux){
        double igv;
        double igvFinal;
        igv=0.18*aux.getPrecio()*aux.getCantidad();
        igvFinal=redondearDecimales(igv,2);
        return igvFinal;
    }
    
    private void jTextFieldNroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNroComprasActionPerformed

    }//GEN-LAST:event_jTextFieldNroComprasActionPerformed

    private void jTextFieldDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sitioWeb2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sitioWeb2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sitioWeb2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sitioWeb2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sitioWeb2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Logearse;
    public javax.swing.JLabel alerta;
    private javax.swing.JButton botCarrito;
    private javax.swing.JButton botonCarrito;
    private javax.swing.JButton botonComprar;
    private javax.swing.JLabel deporteProd;
    private javax.swing.JLabel fondoWeb2;
    private javax.swing.JButton jButtonRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldIGV;
    private javax.swing.JTextField jTextFieldImporte;
    private javax.swing.JTextField jTextFieldNeto;
    private javax.swing.JTextField jTextFieldNroCompras;
    private javax.swing.JList<String> listTalla;
    private javax.swing.JList<String> listaProducto;
    private javax.swing.JLabel mostrarProd;
    private javax.swing.JButton mostrarProductos;
    private javax.swing.JLabel nombreProd;
    private javax.swing.JLabel numeroProd;
    private javax.swing.JLabel precioProd;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JLabel tallaProd;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JLabel textDeporte;
    private javax.swing.JLabel textDescripcion;
    private javax.swing.JLabel textPrecio;
    private javax.swing.JLabel tituloCarrito;
    private javax.swing.JLabel tituloProducto;
    // End of variables declaration//GEN-END:variables
}
