/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import auxiliares.archivos;
import auxiliares.clienteRegistrado;
import clases.*;
import estructuras.*;
import java.awt.Image;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class sitioWeb extends javax.swing.JFrame {

    /**
     * Creates new form sitioWeb
     */
    public sitioWeb() {
        initComponents();
        fondoLogear();
        fondoLogin();
        fondoCarrito();
        fondoWeb2();
        fondoLogin2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logearse = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProducto = new javax.swing.JList<>();
        tituloProducto = new javax.swing.JLabel();
        nombreProd = new javax.swing.JLabel();
        precioProd = new javax.swing.JLabel();
        tallaProd = new javax.swing.JLabel();
        numeroProd = new javax.swing.JLabel();
        deporteProd = new javax.swing.JLabel();
        textPrecio = new javax.swing.JLabel();
        textDeporte = new javax.swing.JLabel();
        botonCarrito = new javax.swing.JButton();
        tituloCarrito = new javax.swing.JLabel();
        mostrarProd = new javax.swing.JLabel();
        mostrarProductos = new javax.swing.JButton();
        textCantidad = new javax.swing.JTextField();
        alerta = new javax.swing.JLabel();
        jButtonRetorno = new javax.swing.JButton();
        textDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTalla = new javax.swing.JList<>();
        fondoWeb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        botonComprar = new javax.swing.JButton();
        botCarrito = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNroCompras = new javax.swing.JTextField();
        jTextFieldIGV = new javax.swing.JTextField();
        jTextFieldDescuento = new javax.swing.JTextField();
        jTextFieldImporte = new javax.swing.JTextField();
        jTextFieldNeto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        fondoLogin = new javax.swing.JLabel();
        sesion = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        contraseñaUser = new javax.swing.JLabel();
        cuentaNueva = new javax.swing.JButton();
        textUsuario = new javax.swing.JTextField();
        contraUser = new javax.swing.JPasswordField();
        fondoUser = new javax.swing.JLabel();
        fondLogin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        listaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProductoMouseClicked(evt);
            }
        });
        listaProducto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProductoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaProducto);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(46, 92, 193, 278);

        tituloProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tituloProducto.setForeground(new java.awt.Color(255, 255, 255));
        tituloProducto.setText("Lista de Productos");
        jPanel1.add(tituloProducto);
        tituloProducto.setBounds(63, 39, 153, 35);

        nombreProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nombreProd.setForeground(new java.awt.Color(255, 255, 255));
        nombreProd.setText("Descripción : ");
        jPanel1.add(nombreProd);
        nombreProd.setBounds(298, 92, 110, 32);

        precioProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        precioProd.setForeground(new java.awt.Color(255, 255, 255));
        precioProd.setText("Precio : ");
        jPanel1.add(precioProd);
        precioProd.setBounds(298, 151, 110, 32);

        tallaProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tallaProd.setForeground(new java.awt.Color(255, 255, 255));
        tallaProd.setText("Talla : ");
        jPanel1.add(tallaProd);
        tallaProd.setBounds(298, 217, 110, 26);

        numeroProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        numeroProd.setForeground(new java.awt.Color(255, 255, 255));
        numeroProd.setText("Cantidad : ");
        jPanel1.add(numeroProd);
        numeroProd.setBounds(298, 277, 110, 26);

        deporteProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        deporteProd.setForeground(new java.awt.Color(255, 255, 255));
        deporteProd.setText("Deporte : ");
        jPanel1.add(deporteProd);
        deporteProd.setBounds(298, 348, 110, 26);

        textPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        textPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textPrecio);
        textPrecio.setBounds(452, 151, 198, 32);

        textDeporte.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        textDeporte.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textDeporte);
        textDeporte.setBounds(450, 350, 93, 32);

        botonCarrito.setFocusable(false);
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCarrito);
        botonCarrito.setBounds(300, 430, 83, 77);

        tituloCarrito.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        tituloCarrito.setForeground(new java.awt.Color(255, 255, 255));
        tituloCarrito.setText("Añadir al carrito");
        jPanel1.add(tituloCarrito);
        tituloCarrito.setBounds(280, 520, 140, 23);

        mostrarProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        mostrarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarProdMouseClicked(evt);
            }
        });
        jPanel1.add(mostrarProd);
        mostrarProd.setBounds(660, 90, 177, 194);

        mostrarProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mostrarProductos.setText("Mostrar");
        mostrarProductos.setFocusable(false);
        mostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProductosActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarProductos);
        mostrarProductos.setBounds(95, 395, 95, 33);

        textCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(textCantidad);
        textCantidad.setBounds(450, 280, 99, 26);

        alerta.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(alerta);
        alerta.setBounds(452, 312, 99, 12);

        jButtonRetorno.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jButtonRetorno.setText("Regresar");
        jButtonRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRetorno);
        jButtonRetorno.setBounds(690, 450, 134, 40);

        textDescripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        textDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textDescripcion);
        textDescripcion.setBounds(452, 92, 198, 32);

        listTalla.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                listTallaAncestorRemoved(evt);
            }
        });
        listTalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTallaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listTalla);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(452, 215, 76, 44);
        jPanel1.add(fondoWeb);
        fondoWeb.setBounds(0, 0, 920, 570);

        Logearse.addTab("Productos", jPanel1);

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaCarrito);

        botonComprar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        botonComprar.setText("Comprar");
        botonComprar.setFocusable(false);
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        botCarrito.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        botCarrito.setText("Mostrar Carrito");
        botCarrito.setFocusable(false);
        botCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCarritoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("RESUMEN DE PEDIDO"));

        jLabel1.setText("Nro de Productos:");

        jLabel2.setText("Importe:");

        jLabel3.setText("IGV: ");

        jLabel4.setText("Descuento:");

        jLabel5.setText("Monto Neto:");

        jTextFieldNroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNroComprasActionPerformed(evt);
            }
        });

        jTextFieldDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIGV)
                            .addComponent(jTextFieldDescuento)
                            .addComponent(jTextFieldNeto)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNroCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jTextFieldImporte)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNroCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(botonComprar)
                .addGap(82, 82, 82)
                .addComponent(botCarrito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonComprar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        Logearse.addTab("Carrito", jPanel2);

        jPanel3.setLayout(null);
        jPanel3.add(fondoLogin);
        fondoLogin.setBounds(113, 31, 346, 58);

        sesion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sesion.setText("Iniciar Sesión");
        sesion.setFocusable(false);
        sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionActionPerformed(evt);
            }
        });
        jPanel3.add(sesion);
        sesion.setBounds(233, 329, 125, 31);

        user.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Usuario : ");
        jPanel3.add(user);
        user.setBounds(69, 134, 107, 30);

        contraseñaUser.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        contraseñaUser.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaUser.setText("Contraseña : ");
        jPanel3.add(contraseñaUser);
        contraseñaUser.setBounds(69, 224, 107, 31);

        cuentaNueva.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cuentaNueva.setText("Crear Cuenta");
        cuentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaNuevaActionPerformed(evt);
            }
        });
        jPanel3.add(cuentaNueva);
        cuentaNueva.setBounds(394, 329, 119, 31);
        jPanel3.add(textUsuario);
        textUsuario.setBounds(233, 137, 280, 30);
        jPanel3.add(contraUser);
        contraUser.setBounds(233, 226, 280, 31);
        jPanel3.add(fondoUser);
        fondoUser.setBounds(614, 111, 178, 177);
        jPanel3.add(fondLogin2);
        fondLogin2.setBounds(0, 0, 920, 570);

        Logearse.addTab("Login", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logearse)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logearse)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fondoLogear(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/login.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoLogin.getWidth(),fondoLogin.getHeight(),Image.SCALE_DEFAULT));
        fondoLogin.setIcon(icono);
    }
    private void fondoLogin(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoLogin.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoUser.getWidth(),fondoUser.getHeight(),Image.SCALE_DEFAULT));
        fondoUser.setIcon(icono);
    }
    private void fondoCarrito(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/carrito.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(botonCarrito.getWidth(),botonCarrito.getHeight(),Image.SCALE_DEFAULT));
        botonCarrito.setIcon(icono);
    }
    private void fondoWeb2(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoWeb.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondoWeb.getWidth(),fondoWeb.getHeight(),Image.SCALE_DEFAULT));
        fondoWeb.setIcon(icono);
    }
    private void fondoLogin2(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/fondoLogin2.jpg"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(fondLogin2.getWidth(),fondLogin2.getHeight(),Image.SCALE_DEFAULT));
        fondLogin2.setIcon(icono);
    }
    private void sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionActionPerformed
        archivos ew=new archivos();
        try {
            ListaDoble<clienteRegistrado> c=ew.cargarCliente();
            boolean t=true;
            for (NodoDoble<clienteRegistrado> co=c.getInicio();co!=null && t==true;co=co.getSiguiente()) {
                if(textUsuario.getText().equals(co.getDato().getCorreo()) && contraUser.getText().trim().equals(co.getDato().getContra())){
                    JOptionPane.showMessageDialog(this, "Usuario correcto");
                    sitioWeb2 p=new sitioWeb2(co.getDato());
                    p.setVisible(true);
                    p.setLocationRelativeTo(null);
                    this.setVisible(false);
                    t=false;
                }
            }
            if(t==true){
                JOptionPane.showMessageDialog(this, "Usuario no encontrado o contraseña incorrecta; por favor ingresar \n"+"datos correctos o crearse una cuenta");
            }
        } catch (IOException | ClassNotFoundException ex) {
//            Logger.getLogger(sitioWeb.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sesionActionPerformed
    Cola<Pedido> colas=new Cola();
    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        try{
        int indice=listaProducto.getSelectedIndex();
        Nodo<Producto> lk=pro.buscar(indice);
        Pedido t=new Pedido();
        for (int i = 0; i < lk.getDato().tallas(); i++) {
            if(Integer.valueOf(textCantidad.getText())>lk.getDato().getStock(i) && listTalla.getSelectedValue().equals(lk.getDato().getTalla(i))){
                JOptionPane.showMessageDialog(this, "Lo sentimos, ha sobrepasado nuestro stock");
            }
            else{
                if(listTalla.getSelectedValue().equals(lk.getDato().getTalla(i))){
                    int sum=lk.getDato().getStock(i)-Integer.parseInt(textCantidad.getText());
                if(sum<10){
                    JOptionPane.showMessageDialog(this, "Lo sentimos, pero alcanzo el limite de nuestro stock.");
                }
                else{
                    t.setDescrip(lk.getDato().getDescrip());
                    t.setTalla(listTalla.getSelectedValue());
                    t.setDeport(lk.getDato().getDeport());
                    int y=0;
                    if(listTalla.getSelectedValue()=="XS"){
                        y=0;
                    }
                    if(listTalla.getSelectedValue()=="S"){
                        y=1;
                    }
                    if(listTalla.getSelectedValue()=="L"){
                        y=2;
                    }
                    if(listTalla.getSelectedValue()=="M"){
                        y=3;
                    }
                    if(listTalla.getSelectedValue()=="XL"){
                        y=4;
                    }
                    if(listTalla.getSelectedValue()=="XXL"){
                        y=5;
                    }
                    t.setPrecio(lk.getDato().getPrecio(y));
                    t.setPrecioTot(lk.getDato().getPrecio(y)*(1.0*Integer.parseInt(textCantidad.getText())));
                    t.setCantidad(Integer.parseInt(textCantidad.getText()));
                    colas.encolar(t);
                    archivos hi=new archivos();
                    hi.guardarCompra(colas);
                    JOptionPane.showMessageDialog(this, "Articulo añadida al carrito");
            }
                }            
        }
        }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese datos números donde corresponda.");
        }
    }//GEN-LAST:event_botonCarritoActionPerformed
    listaSimple<Producto> pro=new listaSimple();
    DefaultListModel modelLista= new DefaultListModel();
    private void mostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProductosActionPerformed
        try {
            archivos po=new archivos();
            pro=po.cargarProducto();
            for(Nodo<Producto> lk=pro.getCab();lk!=null;lk=lk.getSiguiente()){
                modelLista.addElement(lk.getDato().getDescrip());
            }
            listaProducto.setModel(modelLista);
            mostrarProductos.setVisible(false);
        } catch (IOException | ClassNotFoundException ex) {
            
        }
    }//GEN-LAST:event_mostrarProductosActionPerformed
    DefaultListModel modelLista2= new DefaultListModel();
    Nodo<Producto> lk=new Nodo<Producto>();
    private void listaProductoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProductoValueChanged
        
    }//GEN-LAST:event_listaProductoValueChanged

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        this.dispose();
        ProcesoCompra com=new ProcesoCompra(colas);
        com.setVisible(true);
        com.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonComprarActionPerformed

    private void botCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCarritoActionPerformed
        try {
            int nroProductos=0;
            double precioTot=0,IGVGeneral=0,IGV=0;
            archivos ar=new archivos();
            Cola<Pedido> lista=ar.cargarCompra();
            String Matriz[][]=new String[lista.Contar()][6];
            Nodo<Pedido> a=lista.getFrente();
            for (int i = 0; i < lista.Contar() && a!=null; i++) {
                Matriz[i][0]=a.getDato().getDescrip();
                Matriz[i][1]=a.getDato().getTalla();
                Matriz[i][2]=String.valueOf(a.getDato().getPrecio());
                Matriz[i][3]=String.valueOf(a.getDato().getPrecioTot());
                Matriz[i][4]=String.valueOf(a.getDato().getCantidad());
                Matriz[i][5]=a.getDato().getDeport();
                nroProductos=nroProductos+a.getDato().getCantidad();
                precioTot=precioTot+a.getDato().getPrecioTot();
                IGV = calcularIGV(a.getDato());
     
                IGVGeneral = IGVGeneral+ IGV;
                a=a.getSiguiente(); 
            }
            tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
                Matriz,
                new String [] {
                    "DESCRIPCION", "TALLA", "PRECIO UNITARIO", "PRECIO TOTAL", "CANTIDAD", "DEPORTE"
                }
            ));
            jTextFieldNroCompras.setText(String.valueOf(nroProductos));
            jTextFieldImporte.setText(String.valueOf(precioTot));
            jTextFieldIGV.setText(String.valueOf(IGVGeneral));
            jTextFieldDescuento.setText(String.valueOf(0));
            jTextFieldNeto.setText(String.valueOf(redondearDecimales(precioTot+IGVGeneral-0,2)));
        } catch (IOException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(menuProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_botCarritoActionPerformed
       
    public  double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
       
    public double calcularIGV(Pedido aux){
        double igv;
        double igvFinal;
        igv=0.18*aux.getPrecio()*aux.getCantidad();
        igvFinal=redondearDecimales(igv,2);
        return igvFinal;
    }
    
    private void textCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCantidadActionPerformed

    private void mostrarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarProdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarProdMouseClicked
    int bandera=-1;
    boolean b=true;
    private void listaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProductoMouseClicked
        if(b==false && bandera!=listaProducto.getSelectedIndex()){
            modelLista2.clear();
            textCantidad.setText("");
        }
        if(evt.getClickCount()==1 && bandera!=listaProducto.getSelectedIndex()){
           int indice=listaProducto.getSelectedIndex();
            lk=pro.buscar(indice);
            textDescripcion.setText(lk.getDato().getDescrip());
            for (int i = 0; i < lk.getDato().tallas(); i++) {
                if(lk.getDato().getTalla(i)!=null){
                    modelLista2.addElement(lk.getDato().getTalla(i));
                }
            }
            listTalla.setModel(modelLista2);
            textDeporte.setText(lk.getDato().getDeport());
            bandera=listaProducto.getSelectedIndex();
            b=false;
            try {
                ImageIcon icon=new ImageIcon(lk.getDato().getFoto());
                Icon icono=new ImageIcon(icon.getImage().getScaledInstance(mostrarProd.getWidth(), mostrarProd.getHeight(),Image.SCALE_DEFAULT));
                mostrarProd.setText(null);
                mostrarProd.setIcon(icono);
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen"+e);
            }
        }
    }//GEN-LAST:event_listaProductoMouseClicked

    private void jButtonRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornoActionPerformed
        menuCliente mo= new menuCliente();
        mo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRetornoActionPerformed

    private void jTextFieldNroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNroComprasActionPerformed
        
    }//GEN-LAST:event_jTextFieldNroComprasActionPerformed

    private void jTextFieldDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescuentoActionPerformed

    private void cuentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaNuevaActionPerformed
        usuario us=new usuario();
        us.setVisible(true);
        us.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_cuentaNuevaActionPerformed

    private void listTallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTallaMouseClicked
        int y=-1;
        if(evt.getClickCount()==1){           
            if(listTalla.getSelectedValue().equals("XS")){
                y=0;
                textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
            }
            if(listTalla.getSelectedValue().equals("S")){
                y=1;
                textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
            }
            if(listTalla.getSelectedValue().equals("L")){
                y=3;
                textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
            }
            if(listTalla.getSelectedValue().equals("M")){
                y=2;
                textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
            }
            if(listTalla.getSelectedValue().equals("XL")){
                y=4;
                textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
            }
            if(listTalla.getSelectedValue().endsWith("XXL")){
                y=5;
                textPrecio.setText(String.valueOf(lk.getDato().getPrecio(y)));
            }
        
        }
    }//GEN-LAST:event_listTallaMouseClicked

    private void listTallaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listTallaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_listTallaAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sitioWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sitioWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sitioWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sitioWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sitioWeb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Logearse;
    public javax.swing.JLabel alerta;
    private javax.swing.JButton botCarrito;
    private javax.swing.JButton botonCarrito;
    private javax.swing.JButton botonComprar;
    private javax.swing.JPasswordField contraUser;
    private javax.swing.JLabel contraseñaUser;
    private javax.swing.JButton cuentaNueva;
    private javax.swing.JLabel deporteProd;
    private javax.swing.JLabel fondLogin2;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JLabel fondoUser;
    private javax.swing.JLabel fondoWeb;
    private javax.swing.JButton jButtonRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldIGV;
    private javax.swing.JTextField jTextFieldImporte;
    private javax.swing.JTextField jTextFieldNeto;
    private javax.swing.JTextField jTextFieldNroCompras;
    private javax.swing.JList<String> listTalla;
    private javax.swing.JList<String> listaProducto;
    private javax.swing.JLabel mostrarProd;
    private javax.swing.JButton mostrarProductos;
    private javax.swing.JLabel nombreProd;
    private javax.swing.JLabel numeroProd;
    private javax.swing.JLabel precioProd;
    private javax.swing.JButton sesion;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JLabel tallaProd;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JLabel textDeporte;
    private javax.swing.JLabel textDescripcion;
    private javax.swing.JLabel textPrecio;
    private javax.swing.JTextField textUsuario;
    private javax.swing.JLabel tituloCarrito;
    private javax.swing.JLabel tituloProducto;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}