/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cliente;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Jorge M
 */
public class TarjetaComprarNR extends javax.swing.JFrame {
    Cliente NoRegistrado = new Cliente();
    /**
     * Creates new form TarjetaComprarNR
     */
    public TarjetaComprarNR() {
        initComponents();
        
    }
    
    public TarjetaComprarNR(Cliente sos){
        initComponents();
        fondoMaster();
        fondoVisa();
        NoRegistrado = sos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltarjeta = new javax.swing.JLabel();
        lbltarjetamaster = new javax.swing.JLabel();
        lbltarjetavisa = new javax.swing.JLabel();
        btnMaster = new javax.swing.JButton();
        btnvisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltarjeta.setFont(new java.awt.Font("Comic Sans MS", 0, 28)); // NOI18N
        lbltarjeta.setText("Tarjetas permitidas");

        lbltarjetamaster.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        lbltarjetamaster.setText("MasterCard");

        lbltarjetavisa.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        lbltarjetavisa.setText("Visa");

        btnMaster.setFocusable(false);
        btnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterActionPerformed(evt);
            }
        });

        btnvisa.setFocusable(false);
        btnvisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lbltarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltarjetavisa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvisa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltarjetamaster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbltarjeta)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbltarjetamaster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbltarjetavisa)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnvisa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fondoMaster(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/mastercard.gif"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(btnMaster.getWidth(),btnMaster.getHeight(),Image.SCALE_DEFAULT));
        btnMaster.setIcon(icono);
    }
    private void fondoVisa(){
        ImageIcon promo=new ImageIcon(getClass().getResource("/imagenes/visa.png"));
        ImageIcon icono=new ImageIcon(promo.getImage().getScaledInstance(btnvisa.getWidth(),btnvisa.getHeight(),Image.SCALE_DEFAULT));
        btnvisa.setIcon(icono);
    }
    private void btnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterActionPerformed
        TarjetaNR master = new TarjetaNR(NoRegistrado);
        master.setVisible(true);
        master.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMasterActionPerformed

    private void btnvisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvisaActionPerformed
        TarjetaNR visa = new TarjetaNR(NoRegistrado);
        visa.setVisible(true);
        visa.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnvisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarjetaComprarNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarjetaComprarNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarjetaComprarNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarjetaComprarNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarjetaComprarNR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaster;
    private javax.swing.JButton btnvisa;
    private javax.swing.JLabel lbltarjeta;
    private javax.swing.JLabel lbltarjetamaster;
    private javax.swing.JLabel lbltarjetavisa;
    // End of variables declaration//GEN-END:variables
}
