/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import auxiliares.*;
import clases.*;
import estructuras.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Paosds
 */
public class tarjeta extends javax.swing.JFrame {
    
       /**
     * Creates new form tarjeta
     */
    
    public tarjeta(clienteRegistrado l) {
        initComponents();
        jo=l;
    }

    private tarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre = new javax.swing.JLabel();
        lbltarjeta = new javax.swing.JLabel();
        ndetarjeta = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        dni = new javax.swing.JLabel();
        ndetarjeta2 = new javax.swing.JTextField();
        ndetarjeta3 = new javax.swing.JTextField();
        ndetarjeta4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombre.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblnombre.setText("N° de DNI:");

        lbltarjeta.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbltarjeta.setText("N° de tarjeta");

        ndetarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndetarjetaActionPerformed(evt);
            }
        });

        btnaceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.setFocusable(false);
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btnregresar.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnregresar.setText("Salir");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        dni.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dni.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dniAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ndetarjeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndetarjeta2ActionPerformed(evt);
            }
        });

        ndetarjeta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndetarjeta3ActionPerformed(evt);
            }
        });

        ndetarjeta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndetarjeta4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblnombre)
                        .addGap(65, 65, 65)
                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbltarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ndetarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(ndetarjeta4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ndetarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(ndetarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltarjeta)
                    .addComponent(ndetarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ndetarjeta4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ndetarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ndetarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaceptar)
                    .addComponent(btnregresar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    clienteRegistrado jo=new clienteRegistrado();
    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
            if( dni.getText().equals("") || ndetarjeta.getText().equals("")|| ndetarjeta2.getText().equals("")|| ndetarjeta3.getText().equals("")|| ndetarjeta4.getText().equals(""))
            {   
            JOptionPane.showMessageDialog(null,"Uno o mas campos estan vacios","Cuidado",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                if(ndetarjeta.getText().length()==4 && ndetarjeta2.getText().length()==4 && ndetarjeta3.getText().length()==4 && ndetarjeta4.getText().length()==4){
                    archivos a=new archivos();
            ListaDoble<clienteRegistrado> lcliente;
            Cola<Pedido> aux;
            listaSimple<Producto>po;
            try {
                lcliente = a.cargarCliente();
                po=a.cargarProducto();
                aux =a.cargarCompra();
                boolean y=false;
                for(NodoDoble<clienteRegistrado> au1=lcliente.getInicio();au1!=null;au1=au1.getSiguiente()){
                if(Integer.parseInt(dni.getText())==au1.getDato().getDni()){
                    while(!aux.vacio()){
                        Nodo<Pedido> p=aux.Decolar();
                        for (Nodo<Producto> au = po.getCab(); au!=null; au=au.getSiguiente()) {
                            if(au.getDato().getDescrip().equals(p.getDato().getDescrip())){
                                for (int i = 0; i <au.getDato().tallas(); i++) {
                                    if(p.getDato().getTalla().equals(au.getDato().getTalla(i)) && au.getDato().getTalla(i)!=null){
                                        
                                        au.getDato().setStock(au.getDato().getStock(i)-p.getDato().getCantidad(),i);
                                        y=true;
                                    }
                                }
                            }
                               
                        }
                    }
                    
                    
                    a.guardarProducto(po);
                    au1.getDato().setNroCompras(aux.Contar());
                }
                
            }
                if(y==true){
                        JOptionPane.showMessageDialog(null,"Gracias por comprar.\n"+"Nota:Elija su comprobante:","Atencion",JOptionPane.INFORMATION_MESSAGE);
                        mediosPago pa=new mediosPago(jo);
                                        pa.setVisible(true);
                                        pa.setLocationRelativeTo(null);
                                        this.setVisible(false);
                    }
            } catch (IOException | ClassNotFoundException ex) {
////                Logger.getLogger(tarjeta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null,"Ingrese datos numéricos donde corresponda");
            }
            
                }
                else{
                    if(ndetarjeta.getText().length()!=4 && ndetarjeta2.getText().length()!=4 && ndetarjeta3.getText().length()!=4 && ndetarjeta4.getText().length()!=4){
                        JOptionPane.showMessageDialog(null,"Ingrese datos correctos.");
                    }
                }
            }
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void ndetarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndetarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndetarjetaActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:   
        tarjeta.this.setVisible(false);
        principal m = new principal();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnregresarActionPerformed

    private void ndetarjeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndetarjeta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndetarjeta2ActionPerformed

    private void ndetarjeta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndetarjeta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndetarjeta3ActionPerformed

    private void ndetarjeta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndetarjeta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndetarjeta4ActionPerformed

    private void dniAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dniAncestorAdded
        dni.setText(String.valueOf(jo.getDni()));
    }//GEN-LAST:event_dniAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltarjeta;
    private javax.swing.JTextField ndetarjeta;
    private javax.swing.JTextField ndetarjeta2;
    private javax.swing.JTextField ndetarjeta3;
    private javax.swing.JTextField ndetarjeta4;
    // End of variables declaration//GEN-END:variables
}